// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P_EcoMoura.Database;

namespace P_EcoMoura.Migrations
{
    [DbContext(typeof(EcoMouraContext))]
    [Migration("20200503050102_BancoInicial")]
    partial class BancoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("P_EcoMoura.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("celular");

                    b.Property<string>("cnpj");

                    b.Property<int?>("idEmpresa");

                    b.Property<int?>("idRota");

                    b.Property<string>("razaoSocial");

                    b.Property<decimal>("saldoBIN");

                    b.Property<byte>("situacao");

                    b.Property<string>("telefone");

                    b.HasKey("id");

                    b.HasIndex("idEmpresa");

                    b.HasIndex("idRota");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("P_EcoMoura.Models.Cliente", b =>
                {
                    b.HasOne("P_EcoMoura.Models.Cliente", "Empresa")
                        .WithMany()
                        .HasForeignKey("idEmpresa");

                    b.HasOne("P_EcoMoura.Models.Cliente", "Rota")
                        .WithMany()
                        .HasForeignKey("idRota");
                });
#pragma warning restore 612, 618
        }
    }
}
